### ISSUE TITLE
3-bit (indexed 8) color level

### ISSUE THREAD

**Issue by Vankka** [KyoriPowered/ansi#35]
This would be the first 8 colors mentioned here https://en.wikipedia.org/wiki/ANSI_escape_code#3-bit_and_4-bit (same as 4 bit/indexed 16, except only the first half)

The use case I'm interested in is Discord ansi code blocks (they only support 3-bit color)

Alternatively if ColorLevel was a interface, I could implement this myself

**Comment by zml2008** [comment]
Added in #36
