### ISSUE TITLE
Proper terminal detection

### ISSUE THREAD

**Issue by zml2008** [KyoriPowered/ansi#6]
We need a way to determine terminal capabilities with some level of accuracy, with system property and application overrides.

**Comment by rymiel** [comment]
> a way to determine terminal capabilities with some level of accuracy

is there basically, via `COLORTERM` and `TERM` stuff, not sure what else you would want

> with system property

`-Dnet.kyori.ansi.colorLevel` and `-Dterminal.ansi=false` have been added

> and application overrides

not sure what this means. You can always just use the overloads where you can pass a ColorLevel manually

**Comment by zml2008** [comment]
This has been completed to a level sufficient for an initial release -- we can expand on detection as needed based on user feedback.
