### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by zml2008** [KyoriPowered/ansi#9]
there isn't much needed, but it would be nice to publish javadoc somewhere, and maybe have a nice web page to give an overview of how to get started.

**Comment by rymiel** [comment]
@zml2008 I'm not sure what's missing

Everything has javadocs, but making them publish somewhere is build system stuff that is beyond my skillset
do you mean a page in https://docs.advntr.dev/? A readme?

**Comment by zml2008** [comment]
I think jd.advntr.dev has been upgarded since this was written to support extra categories, plus a standalone docs page. Probably docs.advntr.dev is best for now? just cuz we already have it set up
